name: Testing w/o distribution stuff

on: 
  push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: ./
      with:
        app_owner_name: ${{ secrets.TEST_USER_ID }}
        api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
        app_file_path: ./sample/com.deploygate.gradlesample.flavor1.apk
        public: true
