name: Testing for updating an existing distribution

on: 
  push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: ./
      with:
        app_owner_name: ${{ secrets.TEST_USER_ID }}
        api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
        app_file_path: ./sample/com.deploygate.gradlesample.flavor1.apk
        distribution_find_by: key
        distribution_id: 51dff2c6a63a68c9825fb8bb90d5c0542f4dca9c
        public: true

